[package]
name = "uepa"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
enum_dispatch = "0.3.8"
image = "0.24.4"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
paste = "1.0.7"
sdl2 = "0.35.2"
snafu = "0.7.1"
